server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Route for the Product Catalog Service
        - id: product-catalog-service-route
          uri: lb://product-catalog-service
          predicates:
            - Path=/api/v1/products/**

        # Route for the User Service
        - id: user-service-register-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
            - id: user-service-auth-route
              uri: lb://user-service
              predicates:
                - Path=/api/v1/auth/**

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "${JWT_SECRET_KEY}"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"