server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Route for the Product Catalog Service
        - id: product-catalog-service-route
          uri: lb://product-catalog-service
          predicates:
            - Path=/api/v1/products/**

        # Route for the User Service (Register)
        - id: user-service-register-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        # Route for the User Service (Auth)
        - id: user-service-auth-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**

        # Route for the Order Service
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**


  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "${JWT_SECRET_KEY}"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
